name: Send Daily Telegram Message

on:
  workflow_dispatch:
    inputs:
      message_slot:
        description: 'Which prayer'
        required: true
        default: 'fajr'

jobs:
  send-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Send message
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          MESSAGE_SLOT: ${{ github.event.inputs.message_slot }}
        run: python bot.py